import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "../components/ui/floating-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 🔽 Pindahkan navItems ke bawah SEMUA deklarasi font dan import!
const navItems = [
  {
    name: "Home",
    link: "https://ureeka-sesi2.vercel.app/"
  },
  {
    name: "About",
    link: "https://ureeka-sesi2.vercel.app/pages/about/"
  },
  {
    name: "Project",
    link: "https://ureeka-sesi2.vercel.app/pages/project/"
  },
  {
    name: "Resume",
    link: "https://ureeka-sesi2.vercel.app/pages/resume/"
  },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FloatingNav navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
